# === Spotify OAuth ===
client_id: "..."
client_secret: "..."
redirect_uri: "http://127.0.0.1:3000/callback" # Copy this into the Redirect URI field, you may change the port if needed.


# === Update Intervals ===
spotify_refresh_interval: 4
refresh_rate: 0.05
offset_seconds: 0


# === Display Format ===
clearing_method: cursor    # clear, cursor, none (clear has occasional flickering)
center_text: true
wrap_protection: "truncate"   # Options: "truncate", "ellipsis", or "none"
format:
  # Metadata section
  - "{color:#f9e2af}Now playing:{reset} {color:#cdd6f4}{playback.item.name} — {playback.item.artists[0].name}{reset}"
  - "{color:#a6adc8}Album:{reset} {playback.item.album.name}"
  - "{color:#a6adc8}Device:{reset} {playback.device.name}"

  # Time + progress
  - "{color:#a6adc8}Time:{reset} {elapsed} / {duration}"
  - "{progress_bar}"
  - ""

  # Lyrics scroll window
  - "{color:#585b70}{line[-2]}{reset}"
  - "{color:#a6adc8}{line[-1]}{reset}"
  - "{color:#94e2d5}{bold}{line[0]}{reset}"
  - "{color:#a6adc8}{line[1]}{reset}"
  - "{color:#585b70}{line[2]}{reset}"

fallback_to_plain: true


# === Behavior Settings ===
auto_hide_when_paused: true
stop_on_track_change: true


# === Progress Bar ===
progress_bar: true
progress_bar_width: 40
progress_bar_fill: "█"
progress_bar_empty: "░"
progress_bar_color: "#94e2d5"
progress_bar_bg_color: "#313244"
progress_bar_format: "[{bar}] {percent:.1f}%"
